name: weather
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: ^5.1.1
  auto_route: ^9.2.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation:
  font_awesome_flutter: ^10.1.0
  intl: any
  json_annotation: ^4.4.0
  marquee_widget: ^1.2.0
  retrofit: ^4.4.1
  rxdart: ^0.28.0
  pine: ^1.0.3
  dio: ^5.7.0
  provider: ^6.1.2
  talker: ^4.4.7
  talker_dio_logger: ^4.4.7
  talker_bloc_logger: ^4.4.7
  curl_logger_dio_interceptor: ^1.0.0
  reactive_forms: ^17.0.1
  flutter_offline: ^4.0.0
  dart_mapper: ^0.2.2
  flutter_essentials_kit: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  flutter_lints: ^5.0.0
  freezed:
  json_serializable: ^6.1.5
  mockito: ^5.1.0
  retrofit_generator: ^9.1.5
  faker: ^2.2.0
  data_fixture_dart: ^2.2.0
  dart_mapper_generator: ^0.2.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/bg/